### ISSUE TITLE
Segfault when calling a wren method from C++

### ISSUE THREAD

**Issue by Dugy** [Nelarius/wrenpp#9] opened 2016-09-25 19:33 UTC
When I try to call a wren method directly from C++, I get a segfault.

I have created a module named _game_, created in it a class named _Cutscene_ and gave it a method _resume()_ (no arguments). I load the module. When I call:
`vm_->executeString("Cutscene.resume()");`
It works all right. But when I try to call it without having wren parse it, using code like this:
`wrenpp::Method resume = vm_->method("game", "Cutscene", "resume()");`
`wrenpp::Value val = resume();`
I get a segfault at Wren++.h:265, from dereferencing a null pointer.

I have also tried to write main as module _main_, result was the same. When I wrote the name of a non-existent function, it threw an exception as it should.

**Comment by Nelarius** [comment] 2016-09-26 16:00
Does `Cutscene.resume()` call any foreign methods by any change? There's actually a [known bug](https://github.com/munificent/wren/issues/362) in Wren which causes a segfault.

**Comment by Dugy** [comment] 2016-09-26 18:02
My bad. I have slightly misremembered it and thought that I can't call wren from functions called from wren. The issue is in fact less bad, because there is an easy workaround for this. Maybe an assertion could be helpful there to prevent problems like this.

**Comment by Nelarius** [comment] 2016-09-27 05:14
I was thinking about just disabling return values from methods entirely, since the segfault in that issue occurs only when you try to get values out of wren. Return values would be gone probably until the issue is fixed in Wren.

What do you think?

**Comment by Dugy** [comment] 2016-09-27 05:26
I used the method call from C++ in order to obtain the return value. When I changed the code to simply execute a line of wren code, I had to add a side effect to get the return value into the wren function. I think that the return value by itself is good.

**Comment by Nelarius** [comment] 2017-03-13 18:37
I'll close this since it's been a while! Feel free to reopen if problems persist.

**Closed by Nelarius** 2017-03-13 18:37 UTC
